import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import { join } from "node:path"
import test from "node:test"

const root = join(import.meta.dirname, "..")

test("macOS desktop app owns runtime lifecycle without npm or PM2", async () => {
  const source = await readFile(join(root, "desktop/macos/OpenChatXApp.swift"), "utf8")
  assert.match(source, /startBackend/u)
  assert.match(source, /startTunnel/u)
  assert.match(source, /WKWebView/u)
  assert.match(source, /applicationSupportDirectory/u)
  assert.doesNotMatch(source, /\bnpm\b/u)
  assert.doesNotMatch(source, /\bpm2\b/iu)
  assert.match(source, /buildMainMenu/u)
  assert.match(source, /NSText\.copy/u)
  assert.match(source, /NSText\.paste/u)
  assert.match(source, /NSText\.cut/u)
  assert.match(source, /NSText\.selectAll/u)
  assert.match(source, /runJavaScriptConfirmPanelWithMessage/u)
})

test("desktop packaging emits an app and DMG with bundled Node and tunnel-client", async () => {
  const source = await readFile(join(root, "scripts/desktop-macos.ts"), "utf8")
  assert.match(source, /OpenChatX\.app/u)
  assert.match(source, /OpenChatX\.dmg/u)
  assert.match(source, /nodejs\.org\/dist/u)
  assert.match(source, /tunnel-client/u)
  assert.match(source, /codesign/u)
  assert.match(source, /hdiutil/u)
  assert.match(source, /attempt <= 3/u)
})

test("Windows desktop app owns runtime lifecycle with WebView2 and Windows Credential Manager", async () => {
  const source = await readFile(join(root, "desktop/windows/Program.cs"), "utf8")
  assert.match(source, /WebView2/u)
  assert.match(source, /StartBackend/u)
  assert.match(source, /StartTunnel/u)
  assert.match(source, /LocalApplicationData/u)
  assert.match(source, /CredWrite/u)
  assert.match(source, /Kill\(entireProcessTree: true\)/u)
  assert.match(source, /uri\.Scheme is "data" or "about" or "blob"/u)
  assert.match(source, /uri\.Scheme is "http" or "https" or "mailto"/u)
  assert.match(source, /NavigationDisposition\.Blocked/u)
  assert.match(source, /DefaultRuntimePort = 8001/u)
  assert.match(source, /openchatx\.toml/u)
  assert.match(source, /--mcp\.server-url/u)
  assert.match(source, /port != 3333/u)
  assert.match(source, /StringComparer\.OrdinalIgnoreCase/u)
  assert.match(source, /GetValueOrDefault\("Path"\)/u)
  assert.doesNotMatch(source, /GetValueOrDefault\("PATH"\)/u)
  assert.match(source, /_statePreparationGate/u)
  assert.match(source, /if \(_statePrepared\) return/u)
  assert.match(source, /AppendLogLine/u)
  assert.match(source, /FileShare\.ReadWrite \| FileShare\.Delete/u)
  assert.doesNotMatch(source, /File\.AppendAllText\(logPath/u)
  assert.match(source, /IsTunnelRunningAsync/u)
  assert.match(source, /TunnelRestartBackoff/u)
  assert.match(source, /TunnelHealthPort/u)
  assert.match(source, /health_port/u)
  assert.match(source, /TunnelHealthListenAddress/u)
  assert.match(source, /TunnelProfile/u)
  assert.match(source, /OpenChatX\/OPENAI_API_KEY/u)
  assert.match(source, /MigrateLegacyTunnelProfile/u)
  assert.doesNotMatch(source, /127\.0\.0\.1:8080\/health\?details=true/u)
  assert.doesNotMatch(source, /"127\.0\.0\.1:8080"/u)
  assert.match(source, /AutoScaleMode = AutoScaleMode\.Dpi/u)
  assert.match(source, /AutoSizeMode = AutoSizeMode\.GrowAndShrink/u)
  assert.doesNotMatch(source, /Height = hasProfile \? 220 : 280/u)
  assert.doesNotMatch(source, /\bpm2\b/iu)
})

test("Windows desktop startup cannot be blocked indefinitely by WebView2 or tunnel profile probing", async () => {
  const source = await readFile(join(root, "desktop/windows/Program.cs"), "utf8")
  assert.match(source, /Shown \+= async/u)
  assert.doesNotMatch(source, /Load \+= async/u)
  assert.match(source, /Task\.Run\(\(\) => _supervisor\.StartAsync\(\)\)/u)
  assert.match(source, /WebViewInitializationTimeout = TimeSpan\.FromSeconds\(15\)/u)
  assert.match(source, /WaitAsync\(WebViewInitializationTimeout\)/u)
  assert.match(source, /OPENCHATX_APP_DATA/u)
  assert.match(source, /Path\.IsPathFullyQualified/u)
  assert.match(source, /OpenChatX-Recovery/u)
  assert.match(source, /startup stage=\{stage\}/u)
  assert.match(source, /HasTunnelProfileAsync/u)
  assert.match(source, /TunnelProfileProbeTimeout = TimeSpan\.FromSeconds\(3\)/u)
  assert.match(source, /WaitForExitAsync\(cancellation\.Token\)/u)
  assert.doesNotMatch(source, /StandardOutput\.ReadToEnd\(\)/u)
  const runtimeStart = source.indexOf("_ = StartRuntimeInBackgroundAsync();")
  const webViewStart = source.indexOf('LogStartupStage("webview-environment-start")')
  assert.ok(runtimeStart >= 0 && webViewStart > runtimeStart)
  assert.doesNotMatch(source, /state-prepare-start/u)
  assert.match(source, /LogsDirectory = Path\.Combine\(_appSupport, "logs"\)/u)
  assert.match(source, /WebViewUserDataDirectory = Path\.Combine\(_appSupport, "webview2"\)/u)
  assert.match(source, /_profileDirectory = Path\.Combine\(_appSupport, "tunnel-profiles"\)/u)
})

test("macOS desktop follows the configured runtime port", async () => {
  const source = await readFile(join(root, "desktop/macos/OpenChatXApp.swift"), "utf8")
  assert.match(source, /defaultRuntimePort = 8001/u)
  assert.match(source, /openchatx\.toml/u)
  assert.match(source, /--mcp\.server-url/u)
  assert.match(source, /rawValue == "3333"/u)
})

test("Windows desktop packaging cross-builds x64 and arm64 with bundled Node and tunnel-client", async () => {
  const source = await readFile(join(root, "scripts/desktop-windows.ts"), "utf8")
  assert.match(source, /win-x64/u)
  assert.match(source, /win-arm64/u)
  assert.match(source, /nodejs\.org\/dist/u)
  assert.match(source, /openai\/tunnel-client\/releases\/download/u)
  assert.match(source, /OpenChatX-windows-/u)
  assert.match(source, /dotnet/u)
  assert.match(source, /signtool/u)
  assert.match(source, /Inno Setup 6/u)
  const installer = await readFile(join(root, "desktop/windows/OpenChatX.iss"), "utf8")
  assert.match(installer, /OpenChatX-Setup/u)
  assert.match(installer, /UsePreviousAppDir=yes/u)
  assert.match(installer, /UsePreviousTasks=yes/u)
  assert.match(installer, /CloseApplications=yes/u)
  assert.match(installer, /RestartApplications=yes/u)
  assert.doesNotMatch(installer, /UninstallDelete/u)
})

test("desktop distributable defaults do not copy repository MCP or provider config", async () => {
  const source = await readFile(join(root, "scripts/desktop-macos.ts"), "utf8")
  assert.match(source, /desktop\/runtime-defaults\/mcp-servers\.json/u)
  assert.match(source, /desktop\/runtime-defaults\/subagents\.json/u)
  const mcpDefaults = JSON.parse(
    await readFile(join(root, "desktop/runtime-defaults/mcp-servers.json"), "utf8")
  )
  const subagentDefaults = JSON.parse(
    await readFile(join(root, "desktop/runtime-defaults/subagents.json"), "utf8")
  )
  assert.deepEqual(mcpDefaults, {})
  assert.deepEqual(subagentDefaults, { providers: {}, models: {} })
})
